<?xml version="1.0"?>

<!--This benchmark is meant to test functional completeness and correctness
of an XPath/XQuery processor with respect to XPath 1.0. This version includes
a Document Type Definition. 

The benchmark is composed of: 

*) a sequence of XML documents. Each document is enclosed in the CDATA section of an 
   element named document and is identified by an ID attribute called id;
*) a sequence of XPath queries. Each query is enclosed in an element named query and 
   is identified by an ID attribute called id.

Each query has an IDREF attribute called against that points to the document
against which the query has been evaluated. Moreover, each query contains the 
following child elements:

*) type (the category of the query), 
*) description (a description of the query in English), 
*) syntax (the query formula in XPath syntax), and 
*) answer (the result of the evaluation of the query against the pointed document,
   enclosed within a CDATA section). 
-->

<!DOCTYPE benchmark [

<!ELEMENT benchmark     (document*,query*)>
<!ELEMENT document      (#PCDATA)>
<!ELEMENT query         (type,description,syntax,answer)>
<!ELEMENT type          (#PCDATA)>
<!ELEMENT description   (#PCDATA)>
<!ELEMENT syntax        (#PCDATA)>
<!ELEMENT answer        (#PCDATA)>

<!ATTLIST benchmark targets   CDATA #REQUIRED 
                    language  CDATA #REQUIRED
                    authors   CDATA #REQUIRED>
<!ATTLIST document id         ID #REQUIRED>
<!ATTLIST query id            ID #REQUIRED
                against       IDREF #REQUIRED>
]>

<benchmark
targets="completeness, correctness, efficiency, data scalability"
language="XPath 1.0"
authors="Massimo Franceschet (staff.science.uva.nl/~francesc)">

<!--This document corresponds to the XMark document generated with a scaling factor 
of 0.0005.-->
<document id="D1">
<![CDATA[
<?xml version="1.0"?>
<!DOCTYPE site [
<!ELEMENT site            (regions, categories, catgraph, people, open_auctions, closed_auctions)>

<!ELEMENT categories      (category+)>
<!ELEMENT category        (name, description)>
<!ATTLIST category        id ID #REQUIRED>
<!ELEMENT name            (#PCDATA)>
<!ELEMENT description     (text | parlist)>
<!ELEMENT text            (#PCDATA | bold | keyword | emph)*>
<!ELEMENT bold        (#PCDATA | bold | keyword | emph)*>
<!ELEMENT keyword     (#PCDATA | bold | keyword | emph)*>
<!ELEMENT emph        (#PCDATA | bold | keyword | emph)*>
<!ELEMENT parlist     (listitem)*>
<!ELEMENT listitem        (text | parlist)*>

<!ELEMENT catgraph        (edge*)>
<!ELEMENT edge            EMPTY>
<!ATTLIST edge            from IDREF #REQUIRED to IDREF #REQUIRED>

<!ELEMENT regions         (africa, asia, australia, europe, namerica, samerica)>
<!ELEMENT africa          (item*)>
<!ELEMENT asia            (item*)>
<!ELEMENT australia       (item*)>
<!ELEMENT namerica        (item*)>
<!ELEMENT samerica        (item*)>
<!ELEMENT europe          (item*)>
<!ELEMENT item            (location, quantity, name, payment, description, shipping, incategory+, mailbox)>
<!ATTLIST item            id ID #REQUIRED
                          featured CDATA #IMPLIED>
<!ELEMENT location        (#PCDATA)>
<!ELEMENT quantity        (#PCDATA)>
<!ELEMENT payment         (#PCDATA)>
<!ELEMENT shipping        (#PCDATA)>
<!ELEMENT reserve         (#PCDATA)>
<!ELEMENT incategory      EMPTY>
<!ATTLIST incategory      category IDREF #REQUIRED>
<!ELEMENT mailbox         (mail*)>
<!ELEMENT mail            (from, to, date, text)>
<!ELEMENT from            (#PCDATA)>
<!ELEMENT to              (#PCDATA)>
<!ELEMENT date            (#PCDATA)>
<!ELEMENT itemref         EMPTY>
<!ATTLIST itemref         item IDREF #REQUIRED>
<!ELEMENT personref       EMPTY>
<!ATTLIST personref       person IDREF #REQUIRED>

<!ELEMENT people          (person*)>
<!ELEMENT person          (name, emailaddress, phone?, address?, homepage?, creditcard?, profile?, watches?)>
<!ATTLIST person          id ID #REQUIRED>
<!ELEMENT emailaddress    (#PCDATA)>
<!ELEMENT phone           (#PCDATA)>
<!ELEMENT address         (street, city, country, province?, zipcode)>
<!ELEMENT street          (#PCDATA)>
<!ELEMENT city            (#PCDATA)>
<!ELEMENT province        (#PCDATA)>
<!ELEMENT zipcode         (#PCDATA)>
<!ELEMENT country         (#PCDATA)>
<!ELEMENT homepage        (#PCDATA)>
<!ELEMENT creditcard      (#PCDATA)>
<!ELEMENT profile         (interest*, education?, gender?, business, age?)>
<!ATTLIST profile         income CDATA #IMPLIED>
<!ELEMENT interest        EMPTY>
<!ATTLIST interest        category IDREF #REQUIRED>
<!ELEMENT education       (#PCDATA)>
<!ELEMENT income          (#PCDATA)>
<!ELEMENT gender          (#PCDATA)>
<!ELEMENT business        (#PCDATA)>
<!ELEMENT age             (#PCDATA)>
<!ELEMENT watches         (watch*)>
<!ELEMENT watch           EMPTY>
<!ATTLIST watch           open_auction IDREF #REQUIRED>

<!ELEMENT open_auctions   (open_auction*)>
<!ELEMENT open_auction    (initial, reserve?, bidder*, current, privacy?, itemref, seller, annotation, quantity, type, interval)>
<!ATTLIST open_auction    id ID #REQUIRED>
<!ELEMENT privacy         (#PCDATA)>
<!ELEMENT initial         (#PCDATA)>
<!ELEMENT bidder          (date, time, personref, increase)>
<!ELEMENT seller          EMPTY>
<!ATTLIST seller          person IDREF #REQUIRED>
<!ELEMENT current         (#PCDATA)>
<!ELEMENT increase        (#PCDATA)>
<!ELEMENT type            (#PCDATA)>
<!ELEMENT interval        (start, end)>
<!ELEMENT start           (#PCDATA)>
<!ELEMENT end             (#PCDATA)>
<!ELEMENT time            (#PCDATA)>
<!ELEMENT status          (#PCDATA)>
<!ELEMENT amount          (#PCDATA)>

<!ELEMENT closed_auctions (closed_auction*)>
<!ELEMENT closed_auction  (seller, buyer, itemref, price, date, quantity, type, annotation?)>
<!ELEMENT buyer           EMPTY>
<!ATTLIST buyer           person IDREF #REQUIRED>
<!ELEMENT price           (#PCDATA)>
<!ELEMENT annotation      (author, description?, happiness)>

<!ELEMENT author          EMPTY>
<!ATTLIST author          person IDREF #REQUIRED>
<!ELEMENT happiness       (#PCDATA)>
]>
<site>
<regions>
<africa>
<item id="item0">
<location>United States</location>
<quantity>1</quantity>
<name>duteous nine eighteen </name>
<payment>Creditcard</payment>
<description>
<parlist>
<listitem>
<text>
page rous lady idle authority capt professes stabs monster petition heave humbly removes rescue runs shady peace most piteous worser oak assembly holes patience but malice whoreson mirrors master tenants smocks yielded <keyword> officer embrace such fears distinction attires </keyword> 
</text>
</listitem>
<listitem>
<text>
shepherd noble supposed dotage humble servilius bitch theirs venus dismal wounds gum merely raise red breaks earth god folds closet captain dying reek 
</text>
</listitem>
</parlist>
</description>
<shipping>Will ship internationally, See description for charges</shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
<mail>
<from>Dominic Takano mailto:Takano@yahoo.com</from>
<to>Mechthild Renear mailto:Renear@acm.org</to>
<date>10/12/1999</date>
<text>
asses scruple learned crowns preventions half whisper logotype weapons doors factious already pestilent sacks dram atwain girdles deserts flood park lest graves discomfort sinful conceiv therewithal motion stained preventions greatly suit observe sinews enforcement <emph> armed </emph> gold gazing set almost catesby turned servilius cook doublet preventions shrunk 
</text>
</mail>
</mailbox>
</item>
</africa>
<asia>
<item id="item1">
<location>United States</location>
<quantity>1</quantity>
<name>great </name>
<payment>Money order, Cash</payment>
<description>
<text>
print deceit arming ros apes unjustly oregon spring hamlet containing leaves italian turn <bold> spirit model favour disposition </bold> approach charg gold promotions despair flow assured terror assembly marry concluded author debase get bourn openly gonzago wisest bane continue cries 
</text>
</description>
<shipping>Will ship internationally</shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
<mail>
<from>Fumitaka Cenzer mailto:Cenzer@savera.com</from>
<to>Lanju Takano mailto:Takano@itc.it</to>
<date>02/24/2000</date>
<text>
entreaty hath fowl prescience bounds roof fiend intellect boughs caught add jests feelingly doubt trojans wisdom greatness tune worship doors fields reads canst france pay progeny wisdom stir mov impious promis clothes hangman trebonius choose men fits preparation <keyword> benefit since eclipse gates </keyword> 
</text>
</mail>
<mail>
<from>Papa Godskesen mailto:Godskesen@uwindsor.ca</from>
<to>Ioana Blumberg mailto:Blumberg@conclusivestrategies.com</to>
<date>08/02/2001</date>
<text>
jealousy back greg folded gauntlets conduct hardness across sickness peter enough royal herb embrace piteous die servilius avoid <keyword> laying chance dungeons pleasant thyself fellow purse steward heaven ambassador terrible doubtfully </keyword> milk sky clouds unbraced put sacrifices seas childish longer flout heavy pitch rosalind orderly music delivery appease 
</text>
</mail>
</mailbox>
</item>
</asia>
<australia>
<item id="item2">
<location>United States</location>
<quantity>1</quantity>
<name>scarce brook </name>
<payment></payment>
<description>
<parlist>
<listitem>
<text>
senses concave valiant star further instruments bankrupts countrymen horrid costard youth necessity tend curiously waken witness navy there honest interest perceive defendant chief traffic where nuptial descent travel prepare agreed voices swears remember peerless doing <keyword> preparation rejoice </keyword> 
</text>
</listitem>
<listitem>
<text>
swear canker barbarian parching coxcomb excess conspiring nobles sounded consider sayings fishified prime may spirit <emph> untruths misgives choughs mew here garments tenfold </emph> error discontent hung beatrice straight muse shame deep twice mann maecenas any conveyance fingers whereupon child case <keyword> season presently victory women beating </keyword> deprive almost wed dreams slew reveal 
</text>
</listitem>
<listitem>
<text>
spotted attend burden camillo field enlarge stead corporal ground tormenting <bold> naturally sanctuary riddle exile coming awake senseless chance famous albans </bold> service cricket limb from clouds amongst shore penker defend quantity dumb churlish uncover swung eros figur sulphur sky birth stare negligent unction shield instance ambition gate injury fort put infants find slavish hugh see afterwards slanders chides eyes minds alb loved endure combating voyage 
</text>
</listitem>
<listitem>
<parlist>
<listitem>
<text>
maintained peril rivall suddenly finds studies weary truth indulgence anatomy assisted imminent may excepted yonder aches regal 
</text>
</listitem>
<listitem>
<text>
<bold> friar prophetess </bold> spirits delays turning cassio finding unpractis steel sweets promises credulity err nym complete star greatly mope sorry experience virtues been offending bed drives faction learnt hurl eleven huge 
</text>
</listitem>
<listitem>
<text>
piece hours cruelly april league winged <keyword> tract element sails course placed fouler four plac joint </keyword> words blessing fortified loving forfeit doctor valiant crying wife county planet charge haughty precious alexander longboat bells lewd kingdoms knife giver frantic raz commend sit sovereignty engaged perceive its art alliance forge bestow perforce complete roof fie confident raging possible cassio teen crave park reign lords sounded our requite fourth confidence high 
</text>
</listitem>
</parlist>
</listitem>
<listitem>
<parlist>
<listitem>
<text>
sent fled bids oswald help answer artillery jealous hugh fingers gladly mows our craving <emph> preventions spurr edmund drunk how faction quickly bolingbroke painfully </emph> valorous line clasp cheek patchery encompassed honest after auspicious home engaged prompt mortimer bird dread jephthah prithee unfold deeds fifty goose either herald temperance coctus took sought fail each ado checking funeral thinks linger advantage bag ridiculous along accomplishment flower glittering school disguis portia beloved crown sheets garish rather forestall vaults doublet embassy ecstasy crimson rheum befall sin devout pedro little exquisite mote messenger lancaster hideous object arrows smites gently skins bora parting desdemona longing third throng character hat sov quit mounts true house field nearest lucrece tidings fought logotype eaten commanding treason censur ripe praises windsor temperate jealous made sleeve scorn throats fits uncape tended science preventions preventions high pipes reprieves <bold> sold </bold> marriage sampson safety distrust witch christianlike plague doubling visited with bleed offenders catching attendants <emph> cars livery stand </emph> denay <keyword> cimber paper admittance tread character </keyword> battlements seen dun irish throw redeem afflicts suspicion 
</text>
</listitem>
<listitem>
<text>
traduc barks twenty secure pursuit believing necessities longs mental lack further observancy uncleanly understanding vault athens lucius sleeps nor safety evidence repay whensoever senses proudest restraint love mouths slaves water athenian willingly hot grieves delphos pavilion sword indeed lepidus taking disguised proffer salt before educational streets things osw rey stern lap studies finger doomsday pots bounty famous manhood observe hopes unless languish <keyword> transformed nourish breeds north </keyword> 
</text>
</listitem>
</parlist>
</listitem>
</parlist>
</description>
<shipping>Will ship internationally</shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
<mail>
<from>Aspi L'Ecuyer mailto:L'Ecuyer@intersys.com</from>
<to>Lesley Jeris mailto:Jeris@zambeel.com</to>
<date>10/09/1998</date>
<text>
necessities chains rosencrantz house heed course lawn diest unvirtuous supposed sees chough swor numbers game roman soundest wrestler sky lodovico beast shivers desolate norfolk forgot paulina wars george while beggar sheath thursday capable presently his protector father orchard enemies believe drains tokens prison charge cloud stab york mild scene true devotion confidence hundred those guiltless pricks sort himself mutiny officers directive wholesome edge acts dion ride draw brings custom chapless beside sex dowry casca goods priam blasphemy prick octavia brain curer thinkest idiot inward missing conspiracy tents scab inundation caesar officer dramatis 
</text>
</mail>
</mailbox>
</item>
</australia>
<europe>
<item id="item3">
<location>Uzbekistan</location>
<quantity>1</quantity>
<name>abhorr execution beckon rue </name>
<payment>Money order, Creditcard, Cash</payment>
<description>
<parlist>
<listitem>
<text>
<keyword> perjur kills insanie unfortunate conjuration deeper confounded belied first guard </keyword> pale profits height desir ashore france strength kept entrench poisons worth fought ignorance moody poniards speaks jack egg offspring victory food double emperor round jewel abbey apparel untainted lass protest start wings acquit lake lady battles further low thief try brook cake mounted officers dean shrunk lowness dew sandy prologue armies suspicion eighty advance thankfulness albany ended experience halt doubted wert kingdom fiend directed pair perhaps 
</text>
</listitem>
<listitem>
<text>
prayer odds rend condemn conrade swearing dispos losses boar little from thought different couch respected human robe dictynna later pays edward babe distemper bards damned mayst sustain while self alcibiades listen weak soil <keyword> view presume loggets feed </keyword> afoot yields erection balthasar fathers datchet thankless lear cause evil cheerfully instance tarried because cough ancient testimony tarquin cousin reported porter beastly jade bark sex slack lear devil devoured amiable mason moss shoulders labour meanest feign eggs encount forbid enobarbus halters nam emilia fiends bearing food inheritor wiser <emph> hedge </emph> functions there capital greasy dark crush your sequest between devout thou strikes demand dost reverent conference least told ado modena jealousy nunnery mistrust nightly worthy closes tall proudly fierce receive nearness safer jacks shut dire mates wind unfortunate monsieur parcels sauced extremities throat dog empty treasury etc detested stand taxations edges mourner sue knavery unlook perseus diadem heartily peer tut compounded art reconcile study thought cockatrice money pity intend thing claud edmund throws torments ropes contrive story slain advise lecher ardea relics keeping treads buckingham defences lag neighbour ourself marshal disordered moderate venus afeard article rot hazards craft crowns <emph> plainness patient </emph> lying knowledge diseases meritorious medicine instead lid happy without them bands answer 
</text>
</listitem>
</parlist>
</description>
<shipping>Will ship only within country</shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
</mailbox>
</item>
<item id="item4">
<location>United States</location>
<quantity>1</quantity>
<name>lived unsur </name>
<payment>Money order, Creditcard, Personal Check</payment>
<description>
<text>
resolve pursue colour body you ourself month writing beside unadvised tent splits through favours following populous garden henceforth shoots function fourscore mangled favorably slain secretly vice distinguish bardolph content hence boy worse bring usurers stew beard longed creep hid pursuivant beholders senators 
</text>
</description>
<shipping></shipping>
<incategory category="category0"/>
<mailbox>
<mail>
<from>Spyrose Marchegay mailto:Marchegay@rutgers.edu</from>
<to>Hiu Steckler mailto:Steckler@memphis.edu</to>
<date>02/02/2001</date>
<text>
causes remove adding tear often rounds underbearing tree purer kibes endless women benefit throw <emph> claim firmness <keyword> arrived sees wrestled multitude repent preventions infamy reproof shalt hearted prais knave doubtless </keyword> deny </emph> merely grave voluble late loath digest horn slave hunger stronger amazed salt killing ross cry dry tongue kiss yields auspicious quietness perpetual ways <keyword> began leg running unjust court mean returning brook creatures appointed paunches henry sights west prunes flutes regiment seems bed </keyword> musicians slumber post 
</text>
</mail>
</mailbox>
</item>
<item id="item5">
<location>Liberia</location>
<quantity>1</quantity>
<name>wine prevention </name>
<payment>Money order, Creditcard</payment>
<description>
<text>
holly walk inform moods stol castle woo deck bulk begin 
</text>
</description>
<shipping></shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
<mail>
<from>Ulf Tiskin mailto:Tiskin@uic.edu</from>
<to>Rasiah Ranai mailto:Ranai@broadquest.com</to>
<date>12/03/1998</date>
<text>
halts advancing kernel hoppedance perfection weight sultry resign scarf whining safe english rod featur gone ground sick ilion christian mine dine yon debate may longing bestow dispense visitation strangely mab spirit forgot panting haply detest doctors hereby their walk hope learned preventions doubtful scene disposition substance prick afterwards seemeth temples illegitimate prostrate enforcement nakedness down suddenly emptier coventry entreat music treble letting pinion breaking thrifty kissing design airy office <keyword> mad withdraw mother beastly worthiest twice girl indifferent suit </keyword> trick overcome unthrifty <emph> fell othello <bold> wolf entreat audaciously down sands sports pilgrimage duellist league holiday cheek that tables merrily knot selves ionia impure </bold> prophet draw throwing solemn yonder </emph> rightful foam worthless polack veronesa antony beget thereby carry untread hales elbow passing yielding kept dotard holofernes onions din audrey says waterdrops carrion tax prithee crowned troubled naked 
</text>
</mail>
</mailbox>
</item>
</europe>
<namerica>
<item id="item6">
<location>United States</location>
<quantity>1</quantity>
<name>recount waters derive sans </name>
<payment>Creditcard, Personal Check</payment>
<description>
<text>
arthur thrive womb wound baseness joy preventions obey vow bawds myrtle said shallow <bold> neglect montague </bold> souls commended <emph> labour </emph> roderigo persuade alter villain wore thunder congeal pawned alack customary deny faithful top office spoken please neighbour office afternoon drum embowell touch sue lifeless leapt called weary congregation yield check falling wives challenge mental fatal hard ancient stands cor dishes therein gramercy discipline farewell dire tricks protest cut horatio brother speech sleeping adultress pitch cave liv nurse drink state plants combating desired requir rebellion afraid repented tree scald stopp wine advise undermine norfolk vilely whet scars companions hanging foolish scene musty fruitful unburthen teacher 
</text>
</description>
<shipping>Will ship only within country, Will ship internationally, Buyer pays fixed shipping charges, See description for charges</shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
</mailbox>
</item>
<item id="item7">
<location>United States</location>
<quantity>1</quantity>
<name>refractory gouty beauty hire </name>
<payment>Money order, Creditcard, Personal Check, Cash</payment>
<description>
<text>
shook laertes afflictions rouse vast happy news humanity buck destroy military lucius lap <keyword> considered forc mourning verona </keyword> waters triumphing officer hastily <emph> resign subject figure hay thwart written signs gout bred distance period glove players change folly </emph> going wat lost song hautboys pick business crocodile leading cave twice frenzy sprightly dislike invite forbids morn devour ambassador seldom speak tickling rejoice triumphant ascanius forward capable disguise compare buys english shame vulcan farther generation for hearts canst devils furrow promise lusty 
</text>
</description>
<shipping>Will ship only within country</shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
<mail>
<from>Youjian Siochi mailto:Siochi@uwaterloo.ca</from>
<to>Nanning Koshiba mailto:Koshiba@savera.com</to>
<date>08/15/1999</date>
<text>
smell bids repeat roaring expense sensible kneel broke england plac seem villains garments therefore produce done hereford redemption princely smil fields plague hearts precepts laboured gentleman joint borrow lay believe rogue silken break suffer desire paper <keyword> main cressid <emph> person whate lily pilgrim flaying therefore meantime similes base </emph> dowry delivering curan press debtor alexandria sugar battle orbed embrac supremacy answering </keyword> cradle shoulder corpse canons domain night forsake yea satisfy between <bold> senators browsing monsters ear players moreover <emph> sir hor shape suspicious taffeta </emph> banquet </bold> forbear unshown frail journey loves swearing proceeds detain eighteen petter stone battle breathless kindness prophesy entomb over wishing conquer provoke his forehead persuaded places needy balth others school feasted rivers tomb honor garland worser wounding brook stoops brooch plucks level samp tent windsor rubs whereof beam signior built suff heavy dull husbands roman favour urge spear gone 
</text>
</mail>
</mailbox>
</item>
<item id="item8">
<location>United States</location>
<quantity>1</quantity>
<name>cheeks </name>
<payment>Money order</payment>
<description>
<parlist>
<listitem>
<text>
here barnardine assault trade friar taking pheasant sentenc scarf corrections brothers charge spur ass agamemnon truepenny saves roots practis impatient diest didest starv seeing beneath interpose gods home black forgot snuff dress dozen napkins <emph> countess northumberland headlong needless angry pleading </emph> better joy <emph> meagre </emph> reap enquire crab wales died violent rear past liberty <emph> braggart armour infer bankrupt winds teeth </emph> case wore pouch crows cognition 
</text>
</listitem>
<listitem>
<text>
odd expedition free chief cressida hearsed shapes supposes silent wealth off friendship congregation soon farm doct ross susan ready empty dedicate shilling whole soul foot beseech higher lifeless hay postmaster distress disposition <bold> inherits </bold> marcus betters pitch betray beam corse player quality ros conduct thersites greediness boast pilgrims startles contented belch hung thus captain early blood par brook jul gain needs above ensign grapes revelling glean thank seeing tenth succession lief wall bands enterprise flat preventions knave wine shield prey key 
</text>
</listitem>
</parlist>
</description>
<shipping>Will ship only within country, Will ship internationally</shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
<mail>
<from>Margus Narahari mailto:Narahari@earthlink.net</from>
<to>Zhaoqian Krivanek mailto:Krivanek@rice.edu</to>
<date>02/28/2000</date>
<text>
peers necessity ungently advised worst visions whistle serving ratcliff <bold> green horribly vizard intends </bold> corrupted moral help dunghill trembles kingdom true worse pill reap office early secure desires hated garland carriage impatient deserts feel challenger evil <bold> editions depart laur hereford richer </bold> prithee lust shortly approve rey should spectacles fiery perfect worshipp foul quod yes 
</text>
</mail>
<mail>
<from>Zahira Bisiani mailto:Bisiani@arizona.edu</from>
<to>Hae Coste mailto:Coste@ncr.com</to>
<date>06/19/2000</date>
<text>
throng grandam awak helpless ventidius tread defeat teem durst wonderful attaint chaste sees fulfill mortality arme expedient attendants themselves performed leading sing villain skill store mischief see consciences sail text speed sons spleen die oft girl atomies commodity honor fall stopp they 
</text>
</mail>
</mailbox>
</item>
<item id="item9" featured="yes">
<location>United States</location>
<quantity>1</quantity>
<name>greedy ensues pays spilling </name>
<payment>Money order, Personal Check</payment>
<description>
<text>
can whom youth soldiers for time vere record penury herself reasons merits villainous whereupon wrote penny mar preventions followed best eternity bestow blots rocks barnardine torn cassio tailor fame forfeit triumphant conceived deem cowardly merciful topgallant flint purgation whosoever ventidius befits forever bankrupt choughs stains certain violated burgundy shadows possesseth men repent predominant burns revelry swore prodigious next tyrant oath noses apart balth trade feasting field importunity expect experience kingly 
</text>
</description>
<shipping>See description for charges</shipping>
<incategory category="category0"/>
<mailbox>
<mail>
<from>Mehrdad Crescenzo mailto:Crescenzo@ac.at</from>
<to>Shunichiro Usas mailto:Usas@ucsd.edu</to>
<date>01/17/1998</date>
<text>
slowness fast princes their tender softly herod messengers horseman corrosive just make countries quirks shut thence beware jewels sland preventions further royal streets has sells daughters influences leontes priest maggot lays dishes display caught navarre durst weight seat <emph> assigns flesh made his third <keyword> seemeth </keyword> peril gain they stroke forsworn scape full determin professes commons </emph> lordship clear operation practice pyrrhus earnest broke devil posterity company text misbegotten oregon 
</text>
</mail>
</mailbox>
</item>
<item id="item10">
<location>Iraq</location>
<quantity>1</quantity>
<name>cross </name>
<payment>Money order, Creditcard, Personal Check, Cash</payment>
<description>
<text>
use ugly serves presentation aweless comparing thereon secretly gallows preventions horridly purposes frailty shrift slack lieutenant hers stop clown amends throw pomp pretty wildly wake expectation sacrament point marr painted seat fords divided delicate mocking active bills filth pledge latin done statue moved converse goot claw show edmundsbury torment tarquin pyrrhus vanities heathen betray lordship forget enforce gods fills overcame burns leg overthrown institutions adverse brought strives occasion event ready troyan shoulders matters sinews liquid ashy gentlewomen authority assay hole selves living near doting modest wiltshire mocker eton profess forgeries butt wade lawful maccabaeus wert forced succeeding becomes wayward got thief obedience wretches yoke run destroy hole frighting enemies permission vowed swinstead body oph crave consorted requite forfeit speed possess peremptory fraughtage confin rules hatred case art knife bruit wiser engross hero restraint bolingbroke run crimes dominions prey egg conduct <bold> abandon slay diomed apprehend <emph> advantage studied stained entrails bone shoulder </emph> </bold> 
</text>
</description>
<shipping>Buyer pays fixed shipping charges</shipping>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<incategory category="category0"/>
<mailbox>
</mailbox>
</item>
</namerica>
<samerica>
<item id="item11">
<location>United States</location>
<quantity>2</quantity>
<name>proof traitor </name>
<payment>Money order, Cash</payment>