=== jackbergus/MonetDBLite-C/pathfinder/benchmarks/XPathMark/Tests/downloads/outcome.dtd
<!ELEMENT benchmark        (indexes,query*)>

<!ELEMENT indexes          (completeness,correctness,
                            times?,speeds?,scalas?,aqrs?,ads?)>
<!ELEMENT completeness     (#PCDATA)>
<!ELEMENT correctness      (#PCDATA)>
<!ELEMENT times            (qrt+)>
<!ELEMENT speeds           (qrs+)>
<!ELEMENT qrt              (#PCDATA)>
<!ELEMENT qrs              (#PCDATA)>
<!ELEMENT scalas           (scala+)>
<!ELEMENT scala            (PCDATA)>
<!ELEMENT aqrs             (#PCDATA)>
<!ELEMENT ads              (#PCDATA)>

<!ELEMENT query            (type,description,syntax,supported,error?,
                            correct,given_answer?,expected_answer?,
                            times?,speeds?,scalas?,aqrs?,ads?)>
<!ELEMENT type             (#PCDATA)>
<!ELEMENT description      (#PCDATA)>
<!ELEMENT syntax           (#PCDATA)>
<!ELEMENT supported        EMPTY>
<!ELEMENT error            (#PCDATA)>
<!ELEMENT correct          EMPTY>
<!ELEMENT given_answer     (#PCDATA)>
<!ELEMENT expected_answer  (#PCDATA)>

<!ATTLIST benchmark engine    CDATA #REQUIRED
                    version   CDATA #REQUIRED>
<!ATTLIST query     id        ID #REQUIRED>
<!ATTLIST indexes   cpu       CDATA #IMPLIED
                    memory    CDATA #IMPLIED
                    os        CDATA #IMPLIED
                    time_unit (msec | csec | dsec | sec)  #IMPLIED
                    time_type (elapsed | cpu) #IMPLIED>
<!ATTLIST supported value     (yes | no) #REQUIRED>
<!ATTLIST correct   value     (yes | no) #REQUIRED>
<!ATTLIST qrt       factor    CDATA #REQUIRED>
<!ATTLIST qrs       factor    CDATA #REQUIRED>
<!ATTLIST scala     factor1   CDATA #REQUIRED
                    factor2   CDATA #REQUIRED>

=== jackbergus/MonetDBLite-C/pathfinder/benchmarks/XPathMark/Tests/downloads/outcome_galax.xml
<?xml version="1.0"?>

<!--This is an outcome of the XPathMark benchmark evaluation on an XML engine. 
Refer to http://staff.science.uva.nl/~francesc/xpathmark/ for more information.-->

<!DOCTYPE benchmark SYSTEM "outcome.dtd">

<benchmark engine="Galax" version="0.4.0">

<indexes>
 <completeness>0.8</completeness>
 <correctness>0.8</correctness>
</indexes>


<query id='Q1'>
<type>axes</type>
<description>All the items</description>
<syntax>/site/regions/*/item</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q2'>
<type>axes</type>
<description>The keywords in annotations of closed auctions</description>
<syntax>/site/closed_auctions/closed_auction/annotation/description/parlist/listitem/text/keyword</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q3'>
<type>axes</type>
<description>All the keywords</description>
<syntax>//keyword</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q4'>
<type>axes</type>
<description>The keywords in a paragraph item</description>
<syntax>/descendant-or-self::listitem/descendant-or-self::keyword</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q5'>
<type>axes</type>
<description>The (either North or South) American items</description>
<syntax>/site/regions/*/item[parent::namerica or parent::samerica]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q6'>
<type>axes</type>
<description>The paragraph items containing a keyword</description>
<syntax>//keyword/ancestor::listitem</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q7'>
<type>axes</type>
<description>The mails containing a keyword</description>
<syntax>//keyword/ancestor-or-self::mail</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q8'>
<type>axes</type>
<description>The open auctions in which a certain person issued a bid before another person</description>
<syntax>/site/open_auctions/open_auction[bidder[personref/@person='person0']/following-sibling::bidder[personref/@person='person1']]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q9'>
<type>axes</type>
<description>The past bidders of a given open auction</description>
<syntax>/site/open_auctions/open_auction[@id='open_auction0']/bidder/preceding-sibling::bidder</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q10'>
<type>axes</type>
<description>The items that follow, in document order, a given item</description>
<syntax>/site/regions/*/item[@id='item0']/following::item</syntax>
<supported value="no"/>
<error>Parsing Error: Unknown XQuery axis following</error>
<correct value="no"/>
</query>

<query id='Q11'>
<type>axes</type>
<description>The bids issued by a certain person that precedes, in document order, the last bid in document order of another person</description>
<syntax>/site/open_auctions/open_auction/bidder[personref/@person='person1']/preceding::bidder[personref/@person='person0']</syntax>
<supported value="no"/>
<error>Parsing Error: Unknown XQuery axis preceding</error>
<correct value="no"/>
</query>

<query id='Q12'>
<type>axes</type>
<description>All the featured items</description>
<syntax>//item[@featured='yes']</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q13'>
<type>axes</type>
<description>The elements having declared an attribute id</description>
<syntax>//*[@id]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q14'>
<type>axes</type>
<description>Person elements in scope of a namespace with prefix xml</description>
<syntax>//person[namespace::xml]</syntax>
<supported value="no"/>
<error>Parsing Error: Unknown XQuery axis namespace</error>
<correct value="no"/>
</query>

<query id='Q15'>
<type>axes</type>
<description>The increases grater than 20</description>
<syntax>//increase[. > 20]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q16'>
<type>node tests</type>
<description>The elements whose namespace URIs are the same as the namespace URI to which the prefix xml is mapped</description>
<syntax>//xml:*</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q17'>
<type>node tests</type>
<description>Any children node of the root</description>
<syntax>/node()</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q18'>
<type>node tests</type>
<description>The children nodes of the root that are comments</description>
<syntax>/comment()</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q19'>
<type>node tests</type>
<description>The children nodes of the root that are processing instructions</description>
<syntax>/processing-instruction()</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q20'>
<type>node tests</type>
<description>The children nodes of the root that are processing instructions with target robots</description>
<syntax>/processing-instruction('robots')</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q21'>
<type>node tests</type>
<description>The text nodes that are contained in the description element of a given item</description>
<syntax>/site/regions/*/item[@id='item0']/description/descendant-or-self::text()</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q22'>
<type>boolean operators</type>
<description>The (either North or South) American items</description>
<syntax>/site/regions/namerica/item | /site/regions/samerica/item</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q23'>
<type>boolean operators</type>
<description>People having an address and either a phone or a homepage</description>
<syntax>/site/people/person[address and (phone or homepage)]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q24'>
<type>boolean operators</type>
<description>People having no homepage</description>
<syntax>/site/people/person[not(homepage)]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q25'>
<type>references</type>
<description>The name of a given person</description>
<syntax>id('person0')/name</syntax>
<supported value="no"/>
<error>Undefined Error:  Signature of function "http://www.w3.org/2004/07/xpath-functions":id with arity 1 undefined
Failed during normalization of function: "http://www.w3.org/2004/07/xpath-functions":id
</error>
<correct value="no"/>
</query>

<query id='Q26'>
<type>references</type>
<description>The open auctions that a given person is watching</description>
<syntax>id(/site/people/person[@id='person1']/watches/watch/@open_auction)</syntax>
<supported value="no"/>
<error>Undefined Error:  Signature of function "http://www.w3.org/2004/07/xpath-functions":id with arity 1 undefined
Failed during normalization of function: "http://www.w3.org/2004/07/xpath-functions":id
</error>
<correct value="no"/>
</query>

<query id='Q27'>
<type>references</type>
<description>The sellers of the open auctions that a given person is watching</description>
<syntax>id(id(/site/people/person[@id='person1']/watches/watch/@open_auction)/seller/@person)</syntax>
<supported value="no"/>
<error>Undefined Error:  Signature of function "http://www.w3.org/2004/07/xpath-functions":id with arity 1 undefined
Failed during normalization of function: "http://www.w3.org/2004/07/xpath-functions":id
</error>
<correct value="no"/>
</query>

<query id='Q28'>
<type>references</type>
<description>The American items bought by a given person</description>
<syntax>id(/site/closed_auctions/closed_auction[buyer/@person='person4']/itemref/@item)[parent::namerica or parent::samerica]</syntax>
<supported value="no"/>
<error>Undefined Error:  Signature of function "http://www.w3.org/2004/07/xpath-functions":id with arity 1 undefined
Failed during normalization of function: "http://www.w3.org/2004/07/xpath-functions":id
</error>
<correct value="no"/>
</query>

<query id='Q29'>
<type>references</type>
<description>The items sold by Alassane Hogan</description>
<syntax>id(/site/closed_auctions/closed_auction[id(seller/@person)/name='Alassane Hogan']/itemref/@item)</syntax>
<supported value="no"/>
<error>Undefined Error:  Signature of function "http://www.w3.org/2004/07/xpath-functions":id with arity 1 undefined
Failed during normalization of function: "http://www.w3.org/2004/07/xpath-functions":id
</error>
<correct value="no"/>
</query>

<query id='Q30'>
<type>functions</type>
<description>The initial and last bidder of all open auctions</description>
<syntax>/site/open_auctions/open_auction/bidder[position()=1 and position()=last()]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q31'>
<type>functions</type>
<description>The open auctions having more than 5 bidders</description>
<syntax>/site/open_auctions/open_auction[count(bidder)>5]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q32'>
<type>functions</type>
<description>The elements with local name item</description>
<syntax>//*[local-name()='item']</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q33'>
<type>functions</type>
<description>The elements with qualified prefixed name svg:item</description>
<syntax>//*[name()='svg:item']</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q34'>
<type>functions</type>
<description>The elements with a defined namespace URI</description>
<syntax>//*[boolean(namespace-uri())]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q35'>
<type>functions</type>
<description>The elements written in Italian language</description>
<syntax>//*[lang('it')]</syntax>
<supported value="yes"/>
<correct value="yes"/>
</query>

<query id='Q36'>
<type>functions</type>
<description>The items whose description contains the word gold</description>
